package model.entity;
// Generated Mar 30, 2019, 4:19:02 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Coupon generated by hbm2java
 */
@Entity
@Table(name = "coupon",
         catalog = "ecommerce"
)
public class Coupon implements java.io.Serializable {

    private int id;
    private String discount;
    private String description;
    private Set<User> users = new HashSet<User>(0);

    public Coupon() {
    }

    public Coupon(int id) {
        this.id = id;
    }

    public Coupon(int id, String discount, Set<User> users) {
        this.id = id;
        this.discount = discount;
        this.users = users;
    }

    @Id

    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "cid", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "discount")
    public String getDiscount() {
        return this.discount;
    }

    public void setDiscount(String discount) {
        this.discount = discount;
    }

    @Column(name = "description")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "user_has_coupon", catalog = "ecommerce", joinColumns = {
        @JoinColumn(name = "couponID", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "userID", nullable = false, updatable = false)})
    public Set<User> getUsers() {
        return this.users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }

}
