package model.entity;
// Generated Mar 30, 2019, 4:19:02 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderHasProducts generated by hbm2java
 */
@Entity
@Table(name="order_has_products"
    ,catalog="ecommerce"
)
public class OrderHasProducts  implements java.io.Serializable {


     private OrderHasProductsId id;
     private Order order;
     private Product product;
     private Integer quantity;

    public OrderHasProducts() {
    }

	
    public OrderHasProducts(OrderHasProductsId id, Order order, Product product) {
        this.id = id;
        this.order = order;
        this.product = product;
    }
    public OrderHasProducts(OrderHasProductsId id, Order order, Product product, Integer quantity) {
       this.id = id;
       this.order = order;
       this.product = product;
       this.quantity = quantity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orderId", column=@Column(name="orderID", nullable=false) ), 
        @AttributeOverride(name="productId", column=@Column(name="productID", nullable=false) ) } )
    public OrderHasProductsId getId() {
        return this.id;
    }
    
    public void setId(OrderHasProductsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orderID", nullable=false, insertable=false, updatable=false)
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productID", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


