package model.entity;
// Generated Mar 30, 2019, 4:19:02 PM by Hibernate Tools 4.3.1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ProductDetails generated by hbm2java
 */
@Entity
@Table(name = "product_details",
        catalog = "ecommerce"
)
public class ProductDetails implements java.io.Serializable {

    private int productId;
    private Product product;
    private String productImage;

    public ProductDetails() {
    }

    public ProductDetails(Product product) {
        this.product = product;
    }

    public ProductDetails(Product product, String productImage) {
        this.product = product;
        this.productImage = productImage;

    }

    // @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "product"))
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "pid", unique = true, nullable = false)
    public int getProductId() {
        return this.productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "productID")
    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    @Column(name = "productImage")
    public String getProductImage() {
        return this.productImage;
    }

    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }

}
