package model.entity;
// Generated Mar 30, 2019, 4:19:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Shipping generated by hbm2java
 */
@Entity
@Table(name="shipping"
    ,catalog="ecommerce"
)
public class Shipping  implements java.io.Serializable {


     private int id;
     private String type;
     private Long cost;
     private Set<Order> orders = new HashSet<Order>(0);

    public Shipping() {
    }

	
    public Shipping(int id) {
        this.id = id;
    }
    public Shipping(int id, String type, Long cost, Set<Order> orders) {
       this.id = id;
       this.type = type;
       this.cost = cost;
       this.orders = orders;
    }
   
     @Id 

    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="type")
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="cost", precision=10, scale=0)
    public Long getCost() {
        return this.cost;
    }
    
    public void setCost(Long cost) {
        this.cost = cost;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shipping")
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


